[package]
name = "readpage"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.5", features = ["cargo", "color"] }
reqwest = {version = "^0.12", features = ["blocking", "charset"] }
thiserror = "1.0.61"

